/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddAutoCompleteDialog: typeof import('./src/components/AddAutoCompleteDialog.vue')['default']
    AddDialog: typeof import('./src/components/AddDialog.vue')['default']
    AppCard: typeof import('./src/components/AppCard.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Column: typeof import('primevue/column')['default']
    ColumnGroup: typeof import('primevue/columngroup')['default']
    ConfirmationDialog: typeof import('./src/components/ConfirmationDialog.vue')['default']
    CustomDatePicker: typeof import('./src/components/CustomDatePicker.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Dialog: typeof import('primevue/dialog')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    IconField: typeof import('primevue/iconfield')['default']
    ImageButton: typeof import('./src/components/ImageButton.vue')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputMask: typeof import('primevue/inputmask')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Menubar: typeof import('primevue/menubar')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    OfficeButton: typeof import('./src/components/OfficeButton.vue')['default']
    OfficeIconButton: typeof import('./src/components/OfficeIconButton.vue')['default']
    Panel: typeof import('primevue/panel')['default']
    Password: typeof import('primevue/password')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RefreshComponent: typeof import('./src/components/RefreshComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Row: typeof import('primevue/row')['default']
    Select: typeof import('primevue/select')['default']
    StatusButton: typeof import('./src/components/StatusButton.vue')['default']
    Textarea: typeof import('primevue/textarea')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
    TheMenu: typeof import('./src/components/TheMenu.vue')['default']
    TheMenuDobranocka: typeof import('./src/components/dobranocka/TheMenuDobranocka.vue')['default']
    ThemeSwitcher: typeof import('./src/components/ThemeSwitcher.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
  }
}
